### PR TITLE
Fix renderer not loading preset on game start

### PR DESCRIPTION
**Pull request by garbear**
Fixes the renderer not loading the last preset when the game is started. Also contains other minor fixes.

### CODE REVIEW

**Comment by garbear** [comment]
A screenshot of the new label:

screenshot006

**Comment by VelocityRa** [comment]
That's better.
In retrospect I should probably remove "Filter" from "Game Boy Filter", they're all filters.
"Game Boy Screen" may be better.

**Comment by garbear** [comment]
I think the names and categories could use some improvement. While we're working on that, should I add a description field to the dialog?

**Comment by VelocityRa** [comment]
Yup. Doesn't need to be very prevalent, the fullscreen preview should probably still be the main focus.

**Comment by garbear** [comment]
If that's the case, should we get rid of the title and time? Give fullscreen a little more prevalence?

**Comment by VelocityRa** [comment]
Yup, never been a fan of that now that you mention it.

**Comment by garbear** [comment]
I disabled the top bar universally throughout the game OSD

screenshot007

**Pull request merged**
