### PR TITLE
Changes for precompiling output shaders PR

### PR DESCRIPTION
**Pull request by garbear**
Changes for https://github.com/xbmc/xbmc/pull/12929

With these changes merged, the PR now looks like: https://github.com/garbear/xbmc/commit/rp-cacheoutshaders2

Untested (win 7 crashes on startup) I'll test on windows 10 shortly

### CODE REVIEW

**Comment by garbear** [comment]
Tested on windows 7 and changing scaling methods still works.

**Comment by VelocityRa** [comment]
Ok, should I squash or include every commit?

**Comment by garbear** [comment]
I'm going to test the case when a shader fails to compile and maybe some error modes first

**Comment by garbear** [comment]
Pushed a fix for a black screen shown when shader fails to compile. Leave the fix separate when you squash the rest.

**Comment by VelocityRa** [comment]
That good https://github.com/xbmc/xbmc/pull/12929?

**Comment by garbear** [comment]
Looks good.

**Pull request closed without merging**
